name: Unlabel on Bitrise Success
on:
  issue_comment:
    types: [created]
jobs:
  unlabel-bitrise:
    permissions:
      contents: read
      pull-requests: write
    # This job only runs for pull request comments, and comments from user 'companycam-machine'
    if: github.event.issue.pull_request && github.event.sender.login == 'semmerich-ccam'
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v1            
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Build Bitrise
            Build Bitrise with Waldo
